# This action builds and deploys website updates to the release branch.
# 

name: Website build
concurrency: build-${{ github.ref }}
on:
  push:
    branches:
      - master
  workflow_dispatch:      # Manual execution
permissions:
  contents: write
jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the website
        uses: ./.github/actions/build-website
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean-exclude: pr/
          folder: .