name: PR preview build
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
          umbrella-dir: pr